import CourseModel from '../models/course';

const courses: CourseModel[] = [
  {
    courseId: 'course-001',
    teacherId: 'teacher-101',
    languageId: 'en',
    title: 'Basic English Grammar',
    categories: ['Grammar', 'Basics'],
    status: 'ACTIVE',
    contentType: 'GRAMMAR_LESSON',
    proficiencyLevel: 'A1',
    subscriptionModel: 'FREE',
    iconUrl: 'https://example.com/icons/grammar1.png',
    createdAt: '2024-01-10T12:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z'
  },
  {
    courseId: 'course-002',
    teacherId: 'teacher-102',
    languageId: 'fr',
    title: 'French Pronunciation Essentials',
    categories: ['Pronunciation'],
    status: 'ACTIVE',
    contentType: 'PRONUNCIATION_LESSON',
    proficiencyLevel: 'A2',
    subscriptionModel: 'PREMIUM',
    iconUrl: 'https://example.com/icons/french1.png',
    createdAt: '2024-02-05T08:00:00Z',
    updatedAt: '2024-05-01T09:30:00Z'
  },
  {
    courseId: 'course-003',
    teacherId: 'teacher-103',
    languageId: 'es',
    title: 'Conversational Spanish',
    categories: ['Dialogue'],
    status: 'INACTIVE',
    contentType: 'DIALOGUE_LESSON',
    proficiencyLevel: 'B1',
    subscriptionModel: 'PARTIALLY_FREE',
    iconUrl: 'https://example.com/icons/spanish1.png',
    createdAt: '2023-12-20T14:00:00Z',
    updatedAt: '2024-01-22T11:00:00Z'
  },
  {
    courseId: 'course-004',
    teacherId: 'teacher-104',
    languageId: 'de',
    title: 'German Course for Beginners',
    categories: ['Course'],
    status: 'ACTIVE',
    contentType: 'COURSE',
    proficiencyLevel: 'A1',
    subscriptionModel: 'FREE',
    iconUrl: 'https://example.com/icons/german1.png',
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-03-12T15:45:00Z'
  },
  {
    courseId: 'course-005',
    teacherId: 'teacher-105',
    languageId: 'it',
    title: 'Italian Grammar Crash Course',
    categories: ['Grammar'],
    status: 'ACTIVE',
    contentType: 'GRAMMAR_LESSON',
    proficiencyLevel: 'B2',
    subscriptionModel: 'PREMIUM',
    iconUrl: 'https://example.com/icons/italian1.png',
    createdAt: '2023-11-10T12:20:00Z',
    updatedAt: '2024-04-01T13:20:00Z'
  },
  {
    courseId: 'course-006',
    teacherId: 'teacher-106',
    languageId: 'ja',
    title: 'Japanese Pronunciation Basics',
    categories: ['Pronunciation'],
    status: 'INACTIVE',
    contentType: 'PRONUNCIATION_LESSON',
    proficiencyLevel: 'A2',
    subscriptionModel: 'FREE',
    iconUrl: 'https://example.com/icons/japanese1.png',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-25T16:00:00Z'
  },
  {
    courseId: 'course-007',
    teacherId: 'teacher-107',
    languageId: 'ru',
    title: 'Russian for Travelers',
    categories: ['Dialogue', 'Basics'],
    status: 'ACTIVE',
    contentType: 'DIALOGUE_LESSON',
    proficiencyLevel: 'A2',
    subscriptionModel: 'PARTIALLY_FREE',
    iconUrl: 'https://example.com/icons/russian1.png',
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-04-20T12:00:00Z'
  },
  {
    courseId: 'course-008',
    teacherId: 'teacher-108',
    languageId: 'zh',
    title: 'Mandarin Grammar Intermediate',
    categories: ['Grammar'],
    status: 'ACTIVE',
    contentType: 'GRAMMAR_LESSON',
    proficiencyLevel: 'B1',
    subscriptionModel: 'PREMIUM',
    iconUrl: 'https://example.com/icons/mandarin1.png',
    createdAt: '2024-02-11T09:00:00Z',
    updatedAt: '2024-03-11T10:15:00Z'
  },
  {
    courseId: 'course-009',
    teacherId: 'teacher-109',
    languageId: 'en',
    title: 'Advanced English Dialogue',
    categories: ['Dialogue'],
    status: 'INACTIVE',
    contentType: 'DIALOGUE_LESSON',
    proficiencyLevel: 'C1',
    subscriptionModel: 'PREMIUM',
    iconUrl: 'https://example.com/icons/english2.png',
    createdAt: '2023-09-10T11:00:00Z',
    updatedAt: '2024-01-10T13:00:00Z'
  },
  {
    courseId: 'course-010',
    teacherId: 'teacher-110',
    languageId: 'ko',
    title: 'Korean Beginner Course',
    categories: ['Course'],
    status: 'ACTIVE',
    contentType: 'COURSE',
    proficiencyLevel: 'A1',
    subscriptionModel: 'FREE',
    iconUrl: 'https://example.com/icons/korean1.png',
    createdAt: '2024-03-05T15:00:00Z',
    updatedAt: '2024-04-15T14:30:00Z'
  },
  {
    courseId: 'course-011',
    teacherId: 'teacher-111',
    languageId: 'pt',
    title: 'Portuguese for Beginners',
    categories: ['Course'],
    status: 'ACTIVE',
    contentType: 'COURSE',
    proficiencyLevel: 'A2',
    subscriptionModel: 'PARTIALLY_FREE',
    iconUrl: 'https://example.com/icons/portuguese1.png',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-02-10T11:00:00Z'
  },
  {
    courseId: 'course-012',
    teacherId: 'teacher-112',
    languageId: 'ar',
    title: 'Arabic Grammar Essentials',
    categories: ['Grammar'],
    status: 'ACTIVE',
    contentType: 'GRAMMAR_LESSON',
    proficiencyLevel: 'B2',
    subscriptionModel: 'PREMIUM',
    iconUrl: 'https://example.com/icons/arabic1.png',
    createdAt: '2024-02-15T12:00:00Z',
    updatedAt: '2024-04-01T14:00:00Z'
  },
  {
    courseId: 'course-013',
    teacherId: 'teacher-113',
    languageId: 'hi',
    title: 'Hindi Pronunciation Guide',
    categories: ['Pronunciation'],
    status: 'INACTIVE',
    contentType: 'PRONUNCIATION_LESSON',
    proficiencyLevel: 'A1',
    subscriptionModel: 'FREE',
    iconUrl: 'https://example.com/icons/hindi1.png',
    createdAt: '2023-12-10T09:00:00Z',
    updatedAt: '2024-01-10T10:30:00Z'
  },
  {
    courseId: 'course-014',
    teacherId: 'teacher-114',
    languageId: 'tr',
    title: 'Turkish Daily Conversations',
    categories: ['Dialogue'],
    status: 'ACTIVE',
    contentType: 'DIALOGUE_LESSON',
    proficiencyLevel: 'B1',
    subscriptionModel: 'PARTIALLY_FREE',
    iconUrl: 'https://example.com/icons/turkish1.png',
    createdAt: '2024-01-18T14:00:00Z',
    updatedAt: '2024-03-20T15:00:00Z'
  },
  {
    courseId: 'course-015',
    teacherId: 'teacher-115',
    languageId: 'pl',
    title: 'Polish Language Starter Pack',
    categories: ['Course', 'Basics'],
    status: 'ACTIVE',
    contentType: 'COURSE',
    proficiencyLevel: 'A1',
    subscriptionModel: 'FREE',
    iconUrl: 'https://example.com/icons/polish1.png',
    createdAt: '2024-04-01T08:00:00Z',
    updatedAt: '2024-05-01T09:00:00Z'
  }
];

export { courses };
