import LessonModel from '../models/lesson';

export const lessons: LessonModel[] = [
  {
    lessonId: 'lesson-1',
    teacherId: 'teacher-1',
    languageId: 'lang-1',
    title: 'Introduction to Pronunciation',
    courseId: 'course-1',
    courseTitle: 'Basic English',
    category: 'Phonetics',
    contentType: 'PRONUNCIATION_LESSON',
    subscriptionModel: 'FREE',
    lessonExamples: ['Hello', 'Goodbye', 'Thank you'],
    status: 'ACTIVE',
    proficiencyLevel: 'A1',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+1',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-05-01T08:00:00Z',
    updatedAt: '2024-05-02T08:00:00Z'
  },
  {
    lessonId: 'lesson-2',
    teacherId: 'teacher-2',
    languageId: 'lang-1',
    title: 'Basic Greetings',
    courseId: 'course-1',
    courseTitle: 'Basic English',
    category: 'Conversation',
    contentType: 'DIALOGUE_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['Hi!', 'How are you?', 'Nice to meet you'],
    status: 'ACTIVE',
    proficiencyLevel: 'A1',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+2',
    isContentPromoted: false,
    isContentDuringTesting: true,
    isContentPublished: false,
    createdAt: '2024-05-03T08:00:00Z',
    updatedAt: '2024-05-04T08:00:00Z'
  },
  {
    lessonId: 'lesson-3',
    teacherId: 'teacher-3',
    languageId: 'lang-2',
    title: 'Grammar Basics',
    courseId: 'course-2',
    courseTitle: 'Grammar Essentials',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'PARTIALLY_FREE',
    lessonExamples: ['Is/Are', 'Has/Have', 'Was/Were'],
    status: 'INACTIVE',
    proficiencyLevel: 'A2',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+3',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: false,
    createdAt: '2024-05-05T08:00:00Z',
    updatedAt: '2024-05-06T08:00:00Z'
  },
  {
    lessonId: 'lesson-4',
    teacherId: 'teacher-1',
    languageId: 'lang-2',
    title: 'Advanced Verbs',
    courseId: 'course-2',
    courseTitle: 'Grammar Essentials',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['run', 'jump', 'swim'],
    status: 'ACTIVE',
    proficiencyLevel: 'B1',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+4',
    isContentPromoted: true,
    isContentDuringTesting: true,
    isContentPublished: true,
    createdAt: '2024-05-07T08:00:00Z',
    updatedAt: '2024-05-08T08:00:00Z'
  },
  {
    lessonId: 'lesson-5',
    teacherId: 'teacher-2',
    languageId: 'lang-3',
    title: 'Conversational Scenarios',
    courseId: 'course-3',
    courseTitle: 'Everyday English',
    category: 'Dialogue',
    contentType: 'DIALOGUE_LESSON',
    subscriptionModel: 'FREE',
    lessonExamples: ['At the store', 'At the airport', 'In the cafe'],
    status: 'ACTIVE',
    proficiencyLevel: 'B2',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+5',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-05-09T08:00:00Z',
    updatedAt: '2024-05-10T08:00:00Z'
  },
  // 10 more lessons below with slight variations
  {
    lessonId: 'lesson-6',
    teacherId: 'teacher-3',
    languageId: 'lang-1',
    title: 'Past Tense Practice',
    courseId: 'course-3',
    courseTitle: 'Everyday English',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'PARTIALLY_FREE',
    lessonExamples: ['ate', 'went', 'saw'],
    status: 'ACTIVE',
    proficiencyLevel: 'B1',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+6',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-05-11T08:00:00Z',
    updatedAt: '2024-05-12T08:00:00Z'
  },
  {
    lessonId: 'lesson-7',
    teacherId: 'teacher-4',
    languageId: 'lang-2',
    title: 'Future Tense Forms',
    courseId: 'course-4',
    courseTitle: 'Tense Mastery',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'FREE',
    lessonExamples: ['will go', 'will see', 'will eat'],
    status: 'INACTIVE',
    proficiencyLevel: 'C1',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+7',
    isContentPromoted: false,
    isContentDuringTesting: true,
    isContentPublished: false,
    createdAt: '2024-05-13T08:00:00Z',
    updatedAt: '2024-05-14T08:00:00Z'
  },
  {
    lessonId: 'lesson-8',
    teacherId: 'teacher-5',
    languageId: 'lang-3',
    title: 'Pronunciation of Vowels',
    courseId: 'course-4',
    courseTitle: 'Tense Mastery',
    category: 'Phonetics',
    contentType: 'PRONUNCIATION_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['a', 'e', 'i'],
    status: 'ACTIVE',
    proficiencyLevel: 'A2',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+8',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-05-15T08:00:00Z',
    updatedAt: '2024-05-16T08:00:00Z'
  },
  {
    lessonId: 'lesson-9',
    teacherId: 'teacher-1',
    languageId: 'lang-1',
    title: 'Listening Practice',
    courseId: 'course-5',
    courseTitle: 'Fluency First',
    category: 'Listening',
    contentType: 'COURSE',
    subscriptionModel: 'PARTIALLY_FREE',
    lessonExamples: ['audio 1', 'audio 2'],
    status: 'INACTIVE',
    proficiencyLevel: 'C2',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+9',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: false,
    createdAt: '2024-05-17T08:00:00Z',
    updatedAt: '2024-05-18T08:00:00Z'
  },
  {
    lessonId: 'lesson-10',
    teacherId: 'teacher-2',
    languageId: 'lang-2',
    title: 'Common Idioms',
    courseId: 'course-5',
    courseTitle: 'Fluency First',
    category: 'Expressions',
    contentType: 'COURSE',
    subscriptionModel: 'FREE',
    lessonExamples: ['Break a leg', 'Hit the books'],
    status: 'ACTIVE',
    proficiencyLevel: 'B2',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+10',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-05-19T08:00:00Z',
    updatedAt: '2024-05-20T08:00:00Z'
  },
  // Lessons 11–15 (shortened for brevity)
  {
    lessonId: 'lesson-11',
    teacherId: 'teacher-3',
    languageId: 'lang-3',
    title: 'Question Formation',
    courseId: 'course-6',
    courseTitle: 'Practical English',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['What?', 'Where?', 'When?'],
    status: 'ACTIVE',
    proficiencyLevel: 'A2',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+11',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-05-21T08:00:00Z',
    updatedAt: '2024-05-22T08:00:00Z'
  },
  {
    lessonId: 'lesson-12',
    teacherId: 'teacher-4',
    languageId: 'lang-1',
    title: 'Polite Requests',
    courseId: 'course-6',
    courseTitle: 'Practical English',
    category: 'Conversation',
    contentType: 'DIALOGUE_LESSON',
    subscriptionModel: 'FREE',
    lessonExamples: ['Could you please?', 'Would you mind?'],
    status: 'ACTIVE',
    proficiencyLevel: 'B1',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+12',
    isContentPromoted: false,
    isContentDuringTesting: true,
    isContentPublished: true,
    createdAt: '2024-05-23T08:00:00Z',
    updatedAt: '2024-05-23T09:00:00Z'
  },
  {
    lessonId: 'lesson-13',
    teacherId: 'teacher-5',
    languageId: 'lang-2',
    title: 'Shopping Phrases',
    courseId: 'course-7',
    courseTitle: 'Travel English',
    category: 'Dialogue',
    contentType: 'DIALOGUE_LESSON',
    subscriptionModel: 'PARTIALLY_FREE',
    lessonExamples: ['How much?', 'I’d like to buy this.'],
    status: 'INACTIVE',
    proficiencyLevel: 'A1',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+13',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: false,
    createdAt: '2024-05-21T08:00:00Z',
    updatedAt: '2024-05-22T08:00:00Z'
  },
  {
    lessonId: 'lesson-14',
    teacherId: 'teacher-1',
    languageId: 'lang-3',
    title: 'Transportation Vocabulary',
    courseId: 'course-7',
    courseTitle: 'Travel English',
    category: 'Vocabulary',
    contentType: 'COURSE',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['Train', 'Bus', 'Taxi'],
    status: 'ACTIVE',
    proficiencyLevel: 'B2',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+14',
    isContentPromoted: true,
    isContentDuringTesting: true,
    isContentPublished: true,
    createdAt: '2024-05-23T10:00:00Z',
    updatedAt: '2024-05-23T11:00:00Z'
  },
  {
    lessonId: 'lesson-15',
    teacherId: 'teacher-2',
    languageId: 'lang-1',
    title: 'Cultural Phrases',
    courseId: 'course-8',
    courseTitle: 'Cultural English',
    category: 'Culture',
    contentType: 'COURSE',
    subscriptionModel: 'FREE',
    lessonExamples: ['Bless you!', 'Cheers!', 'Excuse me'],
    status: 'ACTIVE',
    proficiencyLevel: 'C1',
    iconUrl: 'https://dummyimage.com/600x400/000/fff&text=Lesson+15',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-05-23T12:00:00Z',
    updatedAt: '2024-05-23T13:00:00Z'
  }
];
