import LessonModel from '../models/lesson';

export const lessons: LessonModel[] = [
  {
    lessonId: 'lesson-001',
    teacherId: 'teacher-001',
    languageId: 'lang-en',
    title: 'Basic English Grammar',
    courseId: 'course-001',
    courseTitle: 'English Foundations',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'FREE',
    lessonExamples: ['I am', 'You are', 'He is'],
    status: 'ACTIVE',
    proficiencyLevel: 'A1',
    iconUrl: 'https://example.com/icons/grammar.png',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z'
  },
  {
    lessonId: 'lesson-002',
    teacherId: 'teacher-002',
    languageId: 'lang-fr',
    title: 'French Vowel Sounds',
    courseId: 'course-002',
    courseTitle: 'French Pronunciation Basics',
    category: 'Pronunciation',
    contentType: 'PRONUNCIATION_LESSON',
    subscriptionModel: 'FREE',
    lessonExamples: ['é', 'è', 'ê'],
    status: 'ACTIVE',
    proficiencyLevel: 'C1',
    iconUrl: 'https://example.com/icons/pronunciation.png',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-02-01T11:00:00Z',
    updatedAt: '2024-02-02T11:00:00Z'
  },
  {
    lessonId: 'lesson-003',
    teacherId: 'teacher-003',
    languageId: 'lang-es',
    title: 'Spanish Restaurant Dialogue',
    courseId: 'course-003',
    courseTitle: 'Conversational Spanish',
    category: 'Dialogue',
    contentType: 'DIALOGUE_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['Quisiera una mesa', 'La cuenta, por favor'],
    status: 'ACTIVE',
    proficiencyLevel: 'A2',
    iconUrl: 'https://example.com/icons/dialogue.png',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-03-10T14:00:00Z',
    updatedAt: '2024-03-12T14:00:00Z'
  },
  {
    lessonId: 'lesson-004',
    teacherId: 'teacher-004',
    languageId: 'lang-de',
    title: 'German Alphabet Introduction',
    courseId: 'course-004',
    courseTitle: 'German Basics',
    category: 'Course',
    contentType: 'COURSE',
    subscriptionModel: 'PARTIALLY_FREE',
    lessonExamples: ['A B C D', 'Ä Ö Ü'],
    status: 'ACTIVE',
    proficiencyLevel: 'B2',
    iconUrl: 'https://example.com/icons/course.png',
    isContentPromoted: false,
    isContentDuringTesting: true,
    isContentPublished: false,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-22T10:00:00Z'
  },
  {
    lessonId: 'lesson-005',
    teacherId: 'teacher-005',
    languageId: 'lang-it',
    title: 'Italian Gendered Nouns',
    courseId: 'course-005',
    courseTitle: 'Essential Italian Grammar',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['il ragazzo', 'la ragazza'],
    status: 'ACTIVE',
    proficiencyLevel: 'C2',
    iconUrl: 'https://example.com/icons/grammar.png',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2023-12-05T09:00:00Z',
    updatedAt: '2023-12-06T09:00:00Z'
  },
  {
    lessonId: 'lesson-006',
    teacherId: 'teacher-006',
    languageId: 'lang-ja',
    title: 'Japanese Consonant Sounds',
    courseId: 'course-006',
    courseTitle: 'Japanese Pronunciation',
    category: 'Pronunciation',
    contentType: 'PRONUNCIATION_LESSON',
    subscriptionModel: 'FREE',
    lessonExamples: ['ka', 'sa', 'ta'],
    status: 'INACTIVE',
    proficiencyLevel: 'A1',
    iconUrl: 'https://example.com/icons/pronunciation.png',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: false,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z'
  },
  {
    lessonId: 'lesson-007',
    teacherId: 'teacher-007',
    languageId: 'lang-ru',
    title: 'Russian Travel Phrases',
    courseId: 'course-007',
    courseTitle: 'Russian in Real Life',
    category: 'Dialogue',
    contentType: 'DIALOGUE_LESSON',
    subscriptionModel: 'PARTIALLY_FREE',
    lessonExamples: ['Где туалет?', 'Сколько это стоит?'],
    status: 'ACTIVE',
    proficiencyLevel: 'C1',
    iconUrl: 'https://example.com/icons/dialogue.png',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-03T10:00:00Z'
  },
  {
    lessonId: 'lesson-008',
    teacherId: 'teacher-008',
    languageId: 'lang-zh',
    title: 'Mandarin Sentence Structure',
    courseId: 'course-008',
    courseTitle: 'Chinese Grammar for Beginners',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['SVO pattern', '我喜欢吃饭'],
    status: 'ACTIVE',
    proficiencyLevel: 'B1',
    iconUrl: 'https://example.com/icons/grammar.png',
    isContentPromoted: false,
    isContentDuringTesting: true,
    isContentPublished: false,
    createdAt: '2024-02-15T12:00:00Z',
    updatedAt: '2024-02-18T12:00:00Z'
  },
  {
    lessonId: 'lesson-009',
    teacherId: 'teacher-009',
    languageId: 'lang-en',
    title: 'Business English Dialogue',
    courseId: 'course-009',
    courseTitle: 'Professional English Skills',
    category: 'Dialogue',
    contentType: 'DIALOGUE_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['Let’s schedule a meeting', 'I’ll follow up by email'],
    status: 'INACTIVE',
    proficiencyLevel: 'B2',
    iconUrl: 'https://example.com/icons/dialogue.png',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: false,
    createdAt: '2023-11-05T10:00:00Z',
    updatedAt: '2023-11-07T10:00:00Z'
  },
  {
    lessonId: 'lesson-010',
    teacherId: 'teacher-010',
    languageId: 'lang-ko',
    title: 'Korean Alphabet Basics',
    courseId: 'course-010',
    courseTitle: 'Learn Hangul',
    category: 'Course',
    contentType: 'COURSE',
    subscriptionModel: 'FREE',
    lessonExamples: ['ㄱ, ㄴ, ㄷ', '안녕하세요'],
    status: 'ACTIVE',
    proficiencyLevel: 'A1',
    iconUrl: 'https://example.com/icons/course.png',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-04-01T09:00:00Z',
    updatedAt: '2024-04-03T09:00:00Z'
  },
  {
    lessonId: 'lesson-011',
    teacherId: 'teacher-011',
    languageId: 'lang-pt',
    title: 'Portuguese Alphabet and Basics',
    courseId: 'course-011',
    courseTitle: 'Portuguese for Beginners',
    category: 'Basics',
    contentType: 'COURSE',
    subscriptionModel: 'PARTIALLY_FREE',
    lessonExamples: ['A B C D', 'Olá, tudo bem?'],
    status: 'ACTIVE',
    proficiencyLevel: 'A2',
    iconUrl: 'https://example.com/icons/portuguese1.png',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-01-25T10:00:00Z',
    updatedAt: '2024-01-30T11:00:00Z'
  },
  {
    lessonId: 'lesson-012',
    teacherId: 'teacher-012',
    languageId: 'lang-ar',
    title: 'Arabic Verb Basics',
    courseId: 'course-012',
    courseTitle: 'Arabic Grammar Essentials',
    category: 'Grammar',
    contentType: 'GRAMMAR_LESSON',
    subscriptionModel: 'PREMIUM',
    lessonExamples: ['كَتَبَ', 'يَكْتُبُ'],
    status: 'ACTIVE',
    proficiencyLevel: 'B2',
    iconUrl: 'https://example.com/icons/arabic1.png',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-02-18T13:00:00Z',
    updatedAt: '2024-02-25T13:00:00Z'
  },
  {
    lessonId: 'lesson-013',
    teacherId: 'teacher-013',
    languageId: 'lang-hi',
    title: 'Hindi Consonant Pronunciation',
    courseId: 'course-013',
    courseTitle: 'Hindi Pronunciation Guide',
    category: 'Pronunciation',
    contentType: 'PRONUNCIATION_LESSON',
    subscriptionModel: 'FREE',
    lessonExamples: ['क, ख, ग, घ', 'त, थ, द, ध'],
    status: 'INACTIVE',
    proficiencyLevel: 'A1',
    iconUrl: 'https://example.com/icons/hindi1.png',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: false,
    createdAt: '2023-12-15T09:30:00Z',
    updatedAt: '2023-12-20T10:00:00Z'
  },
  {
    lessonId: 'lesson-014',
    teacherId: 'teacher-014',
    languageId: 'lang-tr',
    title: 'Turkish Conversation at a Cafe',
    courseId: 'course-014',
    courseTitle: 'Turkish Daily Conversations',
    category: 'Dialogue',
    contentType: 'DIALOGUE_LESSON',
    subscriptionModel: 'PARTIALLY_FREE',
    lessonExamples: ['Bir kahve lütfen', 'Hesap ne kadar?'],
    status: 'ACTIVE',
    proficiencyLevel: 'B1',
    iconUrl: 'https://example.com/icons/turkish1.png',
    isContentPromoted: true,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-01-20T10:30:00Z',
    updatedAt: '2024-01-25T10:30:00Z'
  },
  {
    lessonId: 'lesson-015',
    teacherId: 'teacher-015',
    languageId: 'lang-pl',
    title: 'Polish Greetings and Basics',
    courseId: 'course-015',
    courseTitle: 'Polish Language Starter Pack',
    category: 'Basics',
    contentType: 'COURSE',
    subscriptionModel: 'FREE',
    lessonExamples: ['Dzień dobry', 'Cześć', 'Jak się masz?'],
    status: 'ACTIVE',
    proficiencyLevel: 'A1',
    iconUrl: 'https://example.com/icons/polish1.png',
    isContentPromoted: false,
    isContentDuringTesting: false,
    isContentPublished: true,
    createdAt: '2024-04-03T08:30:00Z',
    updatedAt: '2024-04-10T09:00:00Z'
  }
];
